#!/bin/bash
cd lab0
chmod u+w lanturn8
rm lanturn8
chmod u+w dusknoir6
chmod u+w dusknoir6/horsea
rm dusknoir6/horsea
rm -r $(find . -iname "Copy*" 2>/dev/null)
rm -r $(find . -iname "gabitelantu*" -type f 2>/dev/null)
chmod -R 777 beldum3
rm -r beldum3
chmod u+w ralts5
chmod u+w ralts5/mandibuzz
rm -r ralts5/mandibuzz