#!/bin/bash
mkdir beldum3
cd beldum3
>slakoth
>mudkip
mkdir golurk
cd ..
mkdir dusknoir6
cd ducknoir6
>horsea
>gabite
mkdir koffing
>pidgeotto
>scyther
cd ..
>hitmonlee7
>lanturn8
mkdir ralts5
cd ralts5
>snorlax
mkdir roserade
mkdir mandibuzz
mkdir beartic
cd ..
>walrein4
