#!/bin/bash
chmod 777 lanturn8
rm lanturn8
chmod 777 dusknoir6
chmod 777 dusknoir6/horsea
rm dusknoir6/horsea
rm -r $(find . -iname "Copy*" 2>/dev/null)
rm -r $(find . -iname "gabitelantu*" -type f 2>/dev/null)
chmod -R 777 beldum3
rm -r beldum3
chmod 777 ralts5
chmod 777 ralts5/mandibuzz
rm -r ralts5/mandibuzz